---
title: "Atletas"
author: "Grupo 2"
date: "2024-10-26"
output: 
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    collapsed: true
    smooth_scroll: true
    theme: journal
    highlight: kate
    df_print: paged
    code_folding: show
---

## Colegio Universitario de Cartago

### Carrera de Big Data

### BD-132 Programacion I

### Proyecto #2

### **Realizado por:** Mariel Rodriguez , Johel Barquero, Pablo Marín y Wedell Orozco

### **Docente:** Ericka Celina Valverde Navarro

### Fecha presentación de investigación:

# Librerias

```{r message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(DT)
```

# Set de Datos

```{r message=FALSE, warning=FALSE,fig.width=20, fig.height=10}
#Dataset original jugadores de fifa21
origi_data21 <- read_csv("players_21.csv", col_names = TRUE)
#Dataset original jugadores de fifa22
origi_data22<-read_csv("players_22.csv", col_names = TRUE)
```

## Conocimiento de los datos

```{r results='hide'}
names(origi_data21)#Columnas del set de datos
#Visión general del set de datos
str(origi_data21)
glimpse(origi_data21)
```
### Selección de columnas necesarias: 
```{r message=FALSE, warning=FALSE}
fdata_21<-origi_data21[,c("short_name","player_positions","overall","potential","value_eur","age", "club_name", "league_name", "nationality_name", "preferred_foot", "pace", "shooting", "passing", "dribbling", "defending", "physic")]

fdata_22<-origi_data22[,c("short_name","player_positions","overall","potential","value_eur","age", "club_name", "league_name", "nationality_name", "preferred_foot", "pace", "shooting", "passing", "dribbling", "defending", "physic")]

```

### Data y dimenciones: 
```{r}
fdata_21
dim(fdata_21)

fdata_22
dim(fdata_22)
```




